### ISSUE TITLE
MacOS release

### ISSUE THREAD

**Issue by caleidoscopio** [Ciock/rolify#11]
I tried compiling it myself on XCode but haven't had the time to look into why I can't simply build it.

Could anyone create a MacOS release of Rolify?

**Comment by Ciock** [comment]
I will give it a try too, just to see the scope of the work needed, then we'll discuss the effort 👍

**Comment by Ciock** [comment]
There was a problem with [audio_service](https://pub.dev/packages/audio_service), we just had to bump the MacOS version to `'10.12.2'`.

Now the app runs, but I found a bug: 
You can upload mp3 files from Finder and play them with the others, but when you reload the app, you no longer have permission to access that file from your Mac.

We should have a closer look at [file_picker](https://pub.dev/packages/file_picker) to see what is missing for macOS.

Anyway, the branch with the bumped version is this #12

**Comment by Ciock** [comment]
Following branch #12 the app works because I disabled the Mac sandbox in debug mode. However, this can't be the fix for a future release on App Store because Apple will not accept that. So you can only run it locally.

We need to find a way to give the app permissions to access files on Mac in a production release.

**Comment by Ciock** [comment]
@caleidoscopio I got it! I just disabled the Mac sandbox on release mode too. I don't know why I only thought about publishing on AppStore... we can just create a .dmg file to install 😅.

You can download the file here https://github.com/Ciock/rolify/releases/tag/v.3.2.0
